FROM node:latest

RUN apt-get update && apt-get install nano tree -y

RUN mkdir app
WORKDIR /app

COPY ./app/package*.json ./
RUN npm install

COPY ./app ./
RUN npm install express --save

RUN npm run build

COPY ./server.js .
EXPOSE 3000

CMD ["node", "server"]